// КК9 — Стартовые данные: Оружие
// damage_level: light / heavy / lethal
// damage_type:  physical / mental
// size:         pocket / finger / small / medium / large / huge / immovable
// equipped:     home / carried / equipped
// condition:    broken / worn / good / perfect
// range:        0 = ближний бой, иначе метры
// ap:           бронепробитие
// rof:          скорострельность
// attackModifier: числовой мод к броску атаки
// conditionChance: шанс ухудшения состояния (0–100)
// statusName:   имя статуса при попадании (разрешается в runtime)

export const WEAPONS_DATA = [

  // ══ РУКОПАШНЫЙ БОЙ ═══════════════════════════════════════
  { name: "Кулаки", skillName: "Рукопашный бой", damageLevel: "light", damageType: "physical", range: 0, size: "pocket", ap: 0, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Базовое безоружное нападение. Всегда при себе.", condition: "good", equipped: "home" },
  { name: "Подручный предмет", skillName: "Рукопашный бой", damageLevel: "light", damageType: "physical", range: 0, size: "small", ap: 0, rof: 1, attackModifier: 0, conditionChance: 10, hasStatus: false, statusName: "", description: "Стул, бутылка, кирпич — что попалось под руку.", condition: "good", equipped: "home" },
  { name: "Кастет", skillName: "Рукопашный бой", damageLevel: "light", damageType: "physical", range: 0, size: "pocket", ap: 1, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: false, statusName: "", description: "Концентрирует удар. Легко скрыть.", condition: "good", equipped: "home" },
  { name: "Электрошокер", skillName: "Рукопашный бой", damageLevel: "light", damageType: "physical", range: 0, size: "pocket", ap: 0, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Электрошок", description: "Контактный. Нужно достать до цели.", condition: "good", equipped: "home" },
  { name: "Дубинка", skillName: "Рукопашный бой", damageLevel: "light", damageType: "physical", range: 0, size: "small", ap: 0, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Полицейская дубинка. Оглушает без летального исхода.", condition: "good", equipped: "home" },

  // ══ КЛИНКОВОЕ ОРУЖИЕ ══════════════════════════════════════
  { name: "Нож", skillName: "Владение клинковым оружием", damageLevel: "light", damageType: "physical", range: 0, size: "pocket", ap: 0, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Универсальный инструмент и оружие.", condition: "good", equipped: "home" },
  { name: "Боевой нож", skillName: "Владение клинковым оружием", damageLevel: "light", damageType: "physical", range: 0, size: "small", ap: 1, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Более длинный, более надёжный клинок. Военного класса.", condition: "good", equipped: "home" },
  { name: "Кинжал", skillName: "Владение клинковым оружием", damageLevel: "light", damageType: "physical", range: 0, size: "small", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Двусторонний клинок. Хорош для скрытого ношения.", condition: "good", equipped: "home" },
  { name: "Бита", skillName: "Владение клинковым оружием", damageLevel: "heavy", damageType: "physical", range: 0, size: "medium", ap: 0, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Классика. Дерево или металл — работает одинаково.", condition: "good", equipped: "home" },
  { name: "Мачете", skillName: "Владение клинковым оружием", damageLevel: "heavy", damageType: "physical", range: 0, size: "medium", ap: 1, rof: 1, attackModifier: 0, conditionChance: 5, hasStatus: true, statusName: "Сильное кровотечение", description: "Рубящий клинок широкого профиля.", condition: "good", equipped: "home" },
  { name: "Шпага", skillName: "Владение клинковым оружием", damageLevel: "heavy", damageType: "physical", range: 0, size: "medium", ap: 2, rof: 1, attackModifier: 1, conditionChance: 5, hasStatus: true, statusName: "Сильное кровотечение", description: "Точность важнее силы. Хорошо пробивает.", condition: "good", equipped: "home" },
  { name: "Меч", skillName: "Владение клинковым оружием", damageLevel: "heavy", damageType: "physical", range: 0, size: "large", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Сильное кровотечение", description: "Прямой боевой клинок. Требует пространства.", condition: "good", equipped: "home" },
  { name: "Катана", skillName: "Владение клинковым оружием", damageLevel: "heavy", damageType: "physical", range: 0, size: "large", ap: 2, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Сильное кровотечение", description: "Японский изогнутый клинок. Режет исключительно.", condition: "good", equipped: "home" },
  { name: "Сабля", skillName: "Владение клинковым оружием", damageLevel: "heavy", damageType: "physical", range: 0, size: "large", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Сильное кровотечение", description: "Изогнутый рубящий клинок кавалерийского типа.", condition: "good", equipped: "home" },

  // ══ ОГНЕСТРЕЛЬНОЕ ОРУЖИЕ ══════════════════════════════════
  { name: "Пистолет", skillName: "Владение огнестрельным оружием", damageLevel: "light", damageType: "physical", range: 30, size: "small", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Стандартный полуавтоматический пистолет. Надёжен и неприхотлив.", condition: "good", equipped: "home" },
  { name: "Компактный пистолет", skillName: "Владение огнестрельным оружием", damageLevel: "light", damageType: "physical", range: 20, size: "pocket", ap: 0, rof: 1, attackModifier: 0, conditionChance: 5, hasStatus: true, statusName: "Кровотечение", description: "Скрытое ношение. Меньше дальность, меньше мощность.", condition: "good", equipped: "home" },
  { name: "Пистолет с глушителем", skillName: "Владение огнестрельным оружием", damageLevel: "light", damageType: "physical", range: 25, size: "small", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Тихий. Для работы в тишине.", condition: "good", equipped: "home" },
  { name: "Пистолет под патрон Магнум", skillName: "Владение огнестрельным оружием", damageLevel: "heavy", damageType: "physical", range: 35, size: "small", ap: 2, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Мощный патрон. Сильная отдача.", condition: "good", equipped: "home" },
  { name: "Револьвер", skillName: "Владение огнестрельным оружием", damageLevel: "light", damageType: "physical", range: 30, size: "small", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Надёжен как гвоздь. Не клинит. Перезарядка медленнее.", condition: "good", equipped: "home" },
  { name: "Тяжёлый револьвер", skillName: "Владение огнестрельным оружием", damageLevel: "heavy", damageType: "physical", range: 40, size: "medium", ap: 2, rof: 1, attackModifier: -1, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Мощь за счёт точности. Тяжёлый, громкий, убедительный.", condition: "good", equipped: "home" },
  { name: "Дробовик", skillName: "Владение огнестрельным оружием", damageLevel: "heavy", damageType: "physical", range: 15, size: "large", ap: 0, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Контузия", description: "На близкой дистанции — разрушительно. Сноп дроби.", condition: "good", equipped: "home" },
  { name: "Обрез", skillName: "Владение огнестрельным оружием", damageLevel: "heavy", damageType: "physical", range: 10, size: "medium", ap: 0, rof: 1, attackModifier: 1, conditionChance: 10, hasStatus: true, statusName: "Контузия", description: "Укороченный дробовик. Скрытный, малонадёжный.", condition: "good", equipped: "home" },
  { name: "Тактический дробовик", skillName: "Владение огнестрельным оружием", damageLevel: "heavy", damageType: "physical", range: 20, size: "large", ap: 1, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Контузия", description: "Полуавтоматический. Больше выстрелов без перезарядки.", condition: "good", equipped: "home" },
  { name: "Пистолет-пулемёт", skillName: "Владение огнестрельным оружием", damageLevel: "heavy", damageType: "physical", range: 50, size: "medium", ap: 1, rof: 3, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Контузия", description: "Компактный автоматический. Хорош в помещениях.", condition: "good", equipped: "home" },
  { name: "Автомат", skillName: "Владение огнестрельным оружием", damageLevel: "lethal", damageType: "physical", range: 150, size: "large", ap: 2, rof: 3, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Сквозное ранение", description: "Штурмовая винтовка. Основное оружие пехоты.", condition: "good", equipped: "home" },
  { name: "Карабин", skillName: "Владение огнестрельным оружием", damageLevel: "lethal", damageType: "physical", range: 100, size: "large", ap: 2, rof: 2, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Сквозное ранение", description: "Укороченная версия штурмовой винтовки. Манёвреннее.", condition: "good", equipped: "home" },
  { name: "Боевая винтовка", skillName: "Владение огнестрельным оружием", damageLevel: "lethal", damageType: "physical", range: 200, size: "large", ap: 3, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Сквозное ранение", description: "Полуавтоматическая под мощный патрон. Точность и пробитие.", condition: "good", equipped: "home" },
  { name: "Снайперская винтовка", skillName: "Владение огнестрельным оружием", damageLevel: "lethal", damageType: "physical", range: 500, size: "huge", ap: 4, rof: 1, attackModifier: 2, conditionChance: 0, hasStatus: true, statusName: "Пробитое лёгкое", description: "Для работы на дальней дистанции. Требует позиции и времени.", condition: "good", equipped: "home" },
  { name: "Крупнокалиберная снайперская винтовка", skillName: "Владение огнестрельным оружием", damageLevel: "lethal", damageType: "physical", range: 800, size: "huge", ap: 6, rof: 1, attackModifier: 2, conditionChance: 0, hasStatus: true, statusName: "Пробитое лёгкое", description: "Противоматериальная. Пробивает лёгкую броню и укрытия.", condition: "good", equipped: "home" },
  { name: "Электрошоковый пистолет", skillName: "Владение огнестрельным оружием", damageLevel: "light", damageType: "physical", range: 10, size: "small", ap: 0, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Электрошок", description: "Выстреливает электроды с проводом. Нелетальное обездвиживание.", condition: "good", equipped: "home" },

  // ══ ДРЕВКОВОЕ ОРУЖИЕ ══════════════════════════════════════
  { name: "Посох", skillName: "Владение древковым оружием", damageLevel: "heavy", damageType: "physical", range: 0, size: "large", ap: 0, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: false, statusName: "", description: "Длинный деревянный шест. Универсален в защите и атаке.", condition: "good", equipped: "home" },
  { name: "Копьё", skillName: "Владение древковым оружием", damageLevel: "lethal", damageType: "physical", range: 0, size: "large", ap: 2, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Колющее оружие с длинным древком. Хорошее пробитие.", condition: "good", equipped: "home" },
  { name: "Алебарда", skillName: "Владение древковым оружием", damageLevel: "lethal", damageType: "physical", range: 0, size: "large", ap: 2, rof: 1, attackModifier: 0, conditionChance: 5, hasStatus: true, statusName: "Кровотечение", description: "Комбинирует копьё и топор. Тяжёлое, требует пространства.", condition: "good", equipped: "home" },
  { name: "Боевой молот", skillName: "Владение древковым оружием", damageLevel: "lethal", damageType: "physical", range: 0, size: "large", ap: 1, rof: 1, attackModifier: -1, conditionChance: 0, hasStatus: true, statusName: "Перелом", description: "Сокрушительный удар. Медленнее, но страшнее.", condition: "good", equipped: "home" },
  { name: "Боевой топор", skillName: "Владение древковым оружием", damageLevel: "lethal", damageType: "physical", range: 0, size: "medium", ap: 2, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Перелом", description: "Рубящий. Мощный одиночный удар.", condition: "good", equipped: "home" },
  { name: "Двуручный топор", skillName: "Владение древковым оружием", damageLevel: "lethal", damageType: "physical", range: 0, size: "large", ap: 2, rof: 1, attackModifier: -1, conditionChance: 0, hasStatus: true, statusName: "Перелом", description: "Максимальный рубящий урон. Требует обеих рук.", condition: "good", equipped: "home" },
  { name: "Нагината", skillName: "Владение древковым оружием", damageLevel: "lethal", damageType: "physical", range: 0, size: "large", ap: 2, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Японское древковое оружие с изогнутым клинком. Элегантно и смертоносно.", condition: "good", equipped: "home" },

  // ══ МЕТАТЕЛЬНОЕ И СТРЕЛКОВОЕ ══════════════════════════════
  { name: "Метательный нож", skillName: "Владение метательным/стрелковым оружием", damageLevel: "light", damageType: "physical", range: 15, size: "pocket", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Лёгкий и острый. Обычно носят несколько.", condition: "good", equipped: "home" },
  { name: "Метательный кинжал", skillName: "Владение метательным/стрелковым оружием", damageLevel: "light", damageType: "physical", range: 12, size: "small", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Тяжелее ножа, чуть менее точен на дальности.", condition: "good", equipped: "home" },
  { name: "Сюрикен", skillName: "Владение метательным/стрелковым оружием", damageLevel: "light", damageType: "physical", range: 10, size: "pocket", ap: 0, rof: 2, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Звёздочки. Маленькие, быстрые, можно бросать по несколько.", condition: "good", equipped: "home" },
  { name: "Лук", skillName: "Владение метательным/стрелковым оружием", damageLevel: "heavy", damageType: "physical", range: 100, size: "large", ap: 1, rof: 1, attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Бесшумный. Требует физической силы и тренировки.", condition: "good", equipped: "home" },
  { name: "Составной лук", skillName: "Владение метательным/стрелковым оружием", damageLevel: "heavy", damageType: "physical", range: 150, size: "large", ap: 2, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Современный высокотехнологичный лук. Мощнее и точнее классического.", condition: "good", equipped: "home" },
  { name: "Арбалет", skillName: "Владение метательным/стрелковым оружием", damageLevel: "heavy", damageType: "physical", range: 80, size: "medium", ap: 2, rof: 1, attackModifier: 1, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "Прост в освоении, мощный. Медленная перезарядка.", condition: "good", equipped: "home" },
  { name: "Арбалет пистолетный", skillName: "Владение метательным/стрелковым оружием", damageLevel: "light", damageType: "physical", range: 30, size: "small", ap: 1, rof: 1, attackModifier: 0, conditionChance: 5, hasStatus: true, statusName: "Кровотечение", description: "Компактный. Легко скрыть, небольшая дальность.", condition: "good", equipped: "home" },
];
