// КК9 — Стартовые данные: Заклинания
// spellType: attack / defense / buff / health_buff / binding / spatial / transforming / prophetic / utility
// duration: 0 = мгновенное, -1 = длительное (см. durationHours)
// upkeepCost: энергия в раунд для поддержания (spatial)

export const SPELLS_DATA = [

  // ══ МЕНТАЛЬНАЯ МАГИЯ ══════════════════════════════════════
  { name: "Либерацио", spellType: "utility", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Ментальная магия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Деперсонализация", description: "Снять статус Ментальное истощение с цели." },
  { name: "Эгида Ментис", spellType: "defense", cost: 2, range: 0, duration: -1, durationHours: 0, uses: 5, upkeepCost: 0, skillName: "Ментальная магия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Деперсонализация", bonuses: { toughness: 1 }, description: "Щит от ментального воздействия — бонус к стойкости против ментальных атак." },
  { name: "Детектио", spellType: "prophetic", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Ментальная магия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Деперсонализация", description: "Проверить есть ли на цели ментальные приказы или внушения." },
  { name: "Фантазма", spellType: "utility", cost: 4, range: 15, duration: -1, durationHours: 0.5, uses: 3, upkeepCost: 0, skillName: "Ментальная магия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Деперсонализация", description: "Создать иллюзию в пространстве — визуальный образ без физической формы." },
  { name: "Ментис Иктус", spellType: "attack", cost: 3, range: 15, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Ментальная магия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Деперсонализация", description: "Ментальный удар — наносит ментальный урон цели." },
  { name: "Телепатия", spellType: "binding", cost: 3, range: 5, duration: -1, durationHours: 0.25, uses: 3, upkeepCost: 0, skillName: "Ментальная магия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Читать поверхностные мысли цели." },

  // ══ ПРОРИЦАНИЕ ═══════════════════════════════════════════
  { name: "Клэрвойянс", spellType: "prophetic", cost: 4, range: 0, duration: -1, durationHours: 0.25, uses: 3, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Слепота", description: "Увидеть удалённое место в реальном времени." },
  { name: "Аура Видео", spellType: "prophetic", cost: 1, range: 5, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Слепота", description: "Почувствовать ауру цели — магический статус, общие намерения, эмоциональный фон." },
  { name: "Окультус", spellType: "prophetic", cost: 5, range: 10, duration: -1, durationHours: 0.25, uses: 3, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Слепота", description: "Видеть скрытые объекты и существа — невидимость не работает." },
  { name: "Мемориа Плаци", spellType: "prophetic", cost: 5, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Глухота", description: "Заглянуть в прошлое места — увидеть значимые события." },
  { name: "Оракулум", spellType: "prophetic", cost: 6, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Глухота", description: "Получить смутный образ ближайшего будущего. Интерпретация за ГМом." },
  { name: "Идентифико", spellType: "prophetic", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Глухота", description: "Определить тип и источник заклинания на объекте или акторе." },
  { name: "Вестигиум", spellType: "prophetic", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 3, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Глухота", description: "Найти и следовать магическому следу существа или заклинания." },
  { name: "Локатор", spellType: "prophetic", cost: 4, range: 0, duration: -1, durationHours: 0.25, uses: 1, upkeepCost: 0, skillName: "Прорицание", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Глухота", description: "Определить направление к известному существу или предмету." },

  // ══ ПИРОМАНТИЯ ═══════════════════════════════════════════
  { name: "Игнис Глобус", spellType: "attack", cost: 5, range: 20, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Пиромантия", noWandNeeded: false, isAoe: true, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Ожог", description: "Огненный шар поражающий всех в зоне. Площадное заклинание." },
  { name: "Флamma", spellType: "attack", cost: 3, range: 15, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Пиромантия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Ожог", description: "Струя огня в одну цель." },
  { name: "Комбустио", spellType: "attack", cost: 2, range: 10, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Пиромантия", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Ожог", snakeEyesStatusName: "Ожог", description: "Поджечь цель — накладывает статус Ожог." },
  { name: "Скутум Игнис", spellType: "defense", cost: 4, range: 0, duration: -1, durationHours: 0, uses: 3, upkeepCost: 0, skillName: "Пиромантия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Ожог", bonuses: { toughness: 1 }, description: "Огненный щит вокруг тела — бонус к стойкости против физических атак." },
  { name: "Карцер Игнис", spellType: "spatial", cost: 6, range: 10, duration: -1, durationHours: 0.25, uses: 1, upkeepCost: 2, skillName: "Пиромантия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Ожог", description: "Огненная клетка удерживающая цель внутри." },
  { name: "Калор Мурус", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 4, uses: 1, upkeepCost: 0, skillName: "Пиромантия", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Ожог", description: "Защита от холода — цель не страдает от холодового урона и статусов." },

  // ══ ЭМПИРЕЙ ══════════════════════════════════════════════
  { name: "Бенедиктум", spellType: "buff", cost: 4, range: 0, duration: -1, durationHours: 1, uses: 5, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Благословение", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Благословить цель — накладывает статус Благословение. Бонус ко всем броскам и энергии." },
  { name: "Спиритус Форте", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 1, uses: 5, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Медитативное состояние", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Укрепить дух и магический канал цели." },
  { name: "Виртус", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 5, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Адреналин", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Даровать физическую силу и выносливость. Накладывает статус Адреналин." },
  { name: "Целеритас", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 5, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Повышенная удача", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Ускорить реакцию и инициативу цели." },
  { name: "Магика Ампликацио", spellType: "buff", cost: 4, range: 0, duration: -1, durationHours: 1, uses: 3, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Усилить магический канал — накладывает статус Медитативное состояние с фокусом на magic." },
  { name: "Малум", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Сглаз", snakeEyesStatusName: "Одержимость (лёгкая)", contestedSkillName: "Сопротивление магии", description: "Проклясть цель — накладывает статус Сглаз." },
  { name: "Инфирмитас", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 1, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Ослабление", snakeEyesStatusName: "Одержимость (лёгкая)", contestedSkillName: "Сопротивление магии", description: "Ослабить физические возможности цели." },
  { name: "Фрактус Анимус", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Подавленность", snakeEyesStatusName: "Одержимость (лёгкая)", contestedSkillName: "Сопротивление магии", description: "Сломить дух цели — накладывает статус Подавленность." },
  { name: "Энергиа Вора", spellType: "binding", cost: 3, range: 10, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Одержимость (лёгкая)", contestedSkillName: "Сопротивление магии", description: "Вытянуть энергию из цели." },
  { name: "Абсолутио", spellType: "utility", cost: 5, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Снять проклятие с цели." },
  { name: "Сигиллум", spellType: "binding", cost: 10, range: 0, duration: -1, durationHours: 12, uses: 1, upkeepCost: 0, skillName: "Эмпирей", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Печать", snakeEyesStatusName: "Одержимость (лёгкая)", contestedSkillName: "Сопротивление магии", description: "Заблокировать магические способности цели на 12 часов." },

  // ══ ЖРЕЧЕСТВО ════════════════════════════════════════════
  { name: "Грация", spellType: "buff", cost: 4, range: 0, duration: -1, durationHours: 1, uses: 5, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Благословение", snakeEyesStatusName: "Паранойя", description: "Даровать благодать бога — накладывает статус Благословение." },
  { name: "Кларор Белли", spellType: "buff", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 5, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: true, active: false, hasStatus: true, statusName: "Адреналин", snakeEyesStatusName: "Паранойя", description: "Воинский клич — накладывает статус Адреналин всем в радиусе 10м." },
  { name: "Эгида Деорум", spellType: "defense", cost: 3, range: 0, duration: -1, durationHours: 0, uses: 5, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Паранойя", bonuses: { toughness: 1 }, description: "Защита богов — бонус к стойкости против любого урона." },
  { name: "Донум Санацио", spellType: "utility", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Паранойя", description: "Снять 1 пип физического или ментального урона по воле бога." },
  { name: "Орацио", spellType: "utility", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Восстановление энергии", snakeEyesStatusName: "Паранойя", description: "Молитва богу — накладывает статус Восстановление энергии." },
  { name: "Дира", spellType: "binding", cost: 5, range: 10, duration: -1, durationHours: 12, uses: 1, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Сглаз", snakeEyesStatusName: "Паранойя", contestedSkillName: "Сопротивление магии", description: "Обрушить проклятие бога на цель — накладывает статус Сглаз." },
  { name: "Кастигацио", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: true, statusName: "Ослабление", snakeEyesStatusName: "Паранойя", contestedSkillName: "Сопротивление магии", description: "Кара богов — накладывает статус Ослабление." },
  { name: "Ира Деорум", spellType: "attack", cost: 4, range: 15, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Паранойя", description: "Обрушить гнев бога — ментальный урон от страха перед divine силой." },
  { name: "Консекрацио", spellType: "spatial", cost: 6, range: 5, duration: -1, durationHours: 24, uses: 1, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Паранойя", description: "Освятить место — защитный ритуал, враждебная магия ослаблена." },
  { name: "Инвокацио", spellType: "utility", cost: 5, range: 0, duration: 0, durationHours: 0, uses: 1, upkeepCost: 0, skillName: "Жречество", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Паранойя", description: "Прямой запрос к богу — ответ нарративно за ГМом." },

  // ══ ГЛАМУР ════════════════════════════════════════════════
  { name: "Морфэ", spellType: "transforming", cost: 4, range: 0, duration: -1, durationHours: 2, uses: 1, upkeepCost: 0, skillName: "Гламур", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Зависимость", description: "Изменить внешность себя или другого — лицо, рост, цвет волос." },
  { name: "Акусма", spellType: "utility", cost: 2, range: 20, duration: -1, durationHours: 0.25, uses: 3, upkeepCost: 0, skillName: "Гламур", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Зависимость", description: "Создать иллюзию звука в любой точке пространства." },
  { name: "Инвизибилис", spellType: "spatial", cost: 5, range: 0, duration: -1, durationHours: 0.5, uses: 1, upkeepCost: 0, skillName: "Гламур", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Зависимость", description: "Сделать цель полностью невидимой." },
  { name: "Фантазма Рей", spellType: "utility", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, upkeepCost: 0, skillName: "Гламур", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Зависимость", description: "Создать иллюзию предмета — выглядит и звучит реально, потрогать нельзя." },
  { name: "Венустас", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 1, uses: 5, upkeepCost: 0, skillName: "Гламур", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Зависимость", description: "Бонус к социальным навыкам — цель кажется неотразимой." },
  { name: "Фидуция", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, upkeepCost: 0, skillName: "Гламур", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Зависимость", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели безусловное доверие к кастующему." },
  { name: "Игнотус", spellType: "utility", cost: 2, range: 0, duration: -1, durationHours: 0.5, uses: 3, upkeepCost: 0, skillName: "Гламур", noWandNeeded: false, isAoe: false, active: false, hasStatus: false, statusName: "", snakeEyesStatusName: "Зависимость", description: "Стать незаметным — никто не обращает внимания. Не невидимость." },
];
