// КК9 — Стартовые данные: Снаряжение
// gearType:    attack / defense / utility
// soakType:    absolute / bonus
// energyRestore: восстанавливает энергию при применении
// healthBufferPip: добавляет пип здоровья (0 = нет)
// healthBufferTrack: physical / mental / both

export const GEAR_DATA = [

  // ══ БРОНЯ И ЗАЩИТА ════════════════════════════════════════
  { name: "Кожаная куртка", gearType: "defense", size: "large", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 4, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Минимальная защита. Лучше чем ничего." },
  { name: "Бронежилет лёгкий", gearType: "defense", size: "medium", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 6, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Скрытый бронежилет. Можно носить под одеждой." },
  { name: "Бронежилет тактический", gearType: "defense", size: "large", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 8, soakBonusModifier: 1, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Военный класс. Заметен, но серьёзно защищает." },
  { name: "Бронежилет тяжёлый", gearType: "defense", size: "large", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "absolute", soakAbsoluteCapacity: 4, soakAbsoluteCurrent: 4, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Противопульный жилет с керамическими пластинами. Тяжёлый, ограничивает движение." },
  { name: "Кевларовый шлем", gearType: "defense", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 4, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Защита головы. Комбинируется с бронежилетом." },
  { name: "Щит полицейский", gearType: "defense", size: "large", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "absolute", soakAbsoluteCapacity: 5, soakAbsoluteCurrent: 5, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Баллистический щит. Требует обеих рук. Надёжная позиционная защита." },
  { name: "Средневековый доспех", gearType: "defense", size: "huge", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "absolute", soakAbsoluteCapacity: 6, soakAbsoluteCurrent: 6, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 1, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Полный латный доспех. Серьёзная защита, серьёзные ограничения подвижности." },
  { name: "Экзоскелет защитный", gearType: "defense", size: "huge", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "absolute", soakAbsoluteCapacity: 8, soakAbsoluteCurrent: 8, soakBonusDie: 6, soakBonusModifier: 2, soakUses: 0, healthBufferPip: 2, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Высокотехнологичная силовая броня. Редкая. Сочетает абсолютную защиту с бонусным кубиком." },
  { name: "Противогаз", gearType: "defense", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 2, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Защита от газов, аэрозолей, дыма. Мод к стойкости против химических атак." },
  { name: "Ментальный блокиратор", gearType: "defense", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 6, soakBonusModifier: 1, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "mental", damageLevel: "light", damageType: "mental", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Устройство подавляющее ментальное воздействие. Редкое. Защищает ментальную шкалу." },

  // ══ ГРАНАТЫ И АТАКУЮЩЕЕ ═══════════════════════════════════
  { name: "Осколочная граната", gearType: "attack", size: "pocket", quantity: 2, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "lethal", damageType: "physical", skillName: "Владение метательным/стрелковым оружием", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Кровотечение", description: "АОЕ. Осколки поражают всех в радиусе. Смертоносна в закрытых пространствах." },
  { name: "Светошумовая граната", gearType: "attack", size: "pocket", quantity: 2, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "Владение метательным/стрелковым оружием", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Оглушение", description: "АОЕ. Нелетальная. Временно выводит из строя всех в радиусе." },
  { name: "Дымовая граната", gearType: "attack", size: "pocket", quantity: 2, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "Владение метательным/стрелковым оружием", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Слепота", description: "АОЕ. Создаёт дымовую завесу. Слепит всех в радиусе." },
  { name: "Газовая граната", gearType: "attack", size: "pocket", quantity: 2, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "Владение метательным/стрелковым оружием", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Отравление", description: "АОЕ. Токсичный газ. Поражает всех без противогаза в радиусе." },
  { name: "Коктейль Молотова", gearType: "attack", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "heavy", damageType: "physical", skillName: "Владение метательным/стрелковым оружием", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Ожог", description: "АОЕ. Создаёт зону огня. Поджигает всё в радиусе." },
  { name: "Электромагнитная граната", gearType: "attack", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "Владение метательным/стрелковым оружием", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Электрошок", description: "АОЕ. ЭМИ. Выводит из строя электронику и шокирует цели." },

  // ══ АЛХИМИЧЕСКИЕ ЗЕЛЬЯ — позитивные ══════════════════════
  { name: "Зелье восстановления энергии (малое)", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 5, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Восстанавливает 5 единиц энергии. Горьковатое на вкус." },
  { name: "Зелье восстановления энергии (большое)", gearType: "utility", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 12, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Восстанавливает 12 единиц энергии. Вкус как у медицины." },
  { name: "Зелье исцеления", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Исцеление", description: "Накладывает статус Исцеление. Ускоряет восстановление физических повреждений." },
  { name: "Зелье адреналина", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Адреналин", description: "Мощный выброс. Временно усиливает реакцию и выносливость." },
  { name: "Зелье концентрации", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "mental", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Концентрация", description: "Обостряет внимание и ясность мышления." },
  { name: "Зелье воодушевления", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "mental", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Воодушевление", description: "Поднимает боевой дух и уверенность." },

  // ══ АЛХИМИЧЕСКИЕ ЗЕЛЬЯ — яды ══════════════════════════════
  { name: "Яд контактный", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Отравление", description: "Наносится на поверхность или оружие. Накладывает Отравление при контакте." },
  { name: "Яд сильнодействующий", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Сильное отравление", description: "Быстродействующий. Сразу накладывает Сильное отравление." },
  { name: "Седативное", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "mental", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Оглушение", description: "Вызывает потерю сознания. Применяется инъекцией или через напиток." },
  { name: "Психотропное вещество", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "mental", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Паранойя", description: "Вызывает параноидальные состояния. Инструмент допроса и дестабилизации." },

  // ══ МЕДИЦИНСКОЕ СНАРЯЖЕНИЕ ════════════════════════════════
  { name: "Аптечка полевая", gearType: "utility", size: "small", quantity: 3, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 1, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Бинты, жгут, антисептик. Добавляет 1 пип физического здоровья." },
  { name: "Медицинский набор", gearType: "utility", size: "medium", quantity: 5, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 2, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Полный набор для полевой медицины. 2 пипа физического здоровья." },
  { name: "Успокоительное", gearType: "utility", size: "pocket", quantity: 2, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 1, healthBufferTrack: "mental", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Снижает тревогу и стресс. 1 пип ментального здоровья." },
  { name: "Дефибриллятор", gearType: "utility", size: "medium", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 3, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Экстренное восстановление сердечного ритма. 3 пипа физического здоровья. Одноразовый." },

  // ══ ТАКТИЧЕСКОЕ СНАРЯЖЕНИЕ ════════════════════════════════
  { name: "Наручники", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Связанность", description: "Стальные наручники. Накладывают статус Связанность на цель." },
  { name: "Пластиковые стяжки", gearType: "utility", size: "pocket", quantity: 5, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Связанность", description: "Одноразовые. Лёгкие и незаметные. Несколько штук." },
  { name: "Верёвка (10м)", gearType: "utility", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: true, statusName: "Связанность", description: "Многофункциональна. Подъём, связывание, ловушки." },
  { name: "Отмычки", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Набор для вскрытия замков. Требует навык Воровство." },
  { name: "Бинокль", gearType: "utility", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Наблюдение на дистанции. Бонус к Наблюдательности на дальних целях." },
  { name: "Ночной прицел", gearType: "utility", size: "small", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Устанавливается на оружие. Устраняет штрафы за темноту." },
  { name: "Фонарик тактический", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Мощный направленный свет. Можно ослепить." },
  { name: "Рация", gearType: "utility", size: "pocket", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Зашифрованная связь. Дальность до 5 км в городе." },
  { name: "Жучок (прослушка)", gearType: "utility", size: "pocket", quantity: 3, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Миниатюрный жучок. Устанавливается незаметно. Комплект из 3 штук." },
  { name: "Верёвка для спуска (30м)", gearType: "utility", size: "medium", quantity: 1, equipped: "home", condition: "good", energyRestore: 0, soakType: "bonus", soakAbsoluteCapacity: 0, soakAbsoluteCurrent: 0, soakBonusDie: 0, soakBonusModifier: 0, soakUses: 0, healthBufferPip: 0, healthBufferTrack: "physical", damageLevel: "light", damageType: "physical", skillName: "", attackModifier: 0, conditionChance: 0, hasStatus: false, statusName: "", description: "Верёвка с карабинами для тактического спуска с высоты." },
];
