// ============================================================
// КК9 — справочник навыков. Взят ровно из seed-abilities.mjs.
// base:true — выдаётся всем при создании. categ: common|learned|magic|personal.
// Нетренированный навык: die 4, modifier -2 (как AbilityDataModel в Foundry).
//
// IMP-05a: каждая запись МОЖЕТ нести два необязательных текстовых поля —
//   description — «Что это» (короткое пояснение навыка)
//   whenToRoll  — «Когда бросать» (в каких ситуациях кидать)
// Они подхватываются всплывающей подсказкой на карточке и в окне прокачки;
// без них показывается обычная однострочная подсказка (никакой регрессии).
// Сам контент (~200 записей) наполняется отдельно в IMP-05b.
// Пример заполнения (наведите на бейдж атрибута навыка на карточке):
//   { name:"Плавание", attr:"endurance", base:true, categ:"learned",
//     description:"...", whenToRoll:"..." },
// ============================================================
export const SKILLS_DATA = [
  { name:"Плавание", attr:"endurance", base:true, categ:"learned",
    description:"Умение держаться на воде и плыть в одежде или со снаряжением.",
    whenToRoll:"Когда нужно переплыть, нырнуть или удержаться на плаву в опасных условиях." },
  { name:"Атлетика", attr:"endurance", base:true, categ:"common",
    description:"Бег, прыжки, лазание и общая физическая ловкость тела.",
    whenToRoll:"При погоне, прыжке через препятствие, лазании или рывке на пределе сил." },
  { name:"Общая эрудиция", attr:"smarts", base:true, categ:"common" },
  { name:"Техника", attr:"smarts", base:true, categ:"learned" },
  { name:"Электроника", attr:"smarts", base:true, categ:"common" },
  { name:"Ориентирование", attr:"smarts", base:true, categ:"learned" },
  { name:"Наблюдательность", attr:"smarts", base:true, categ:"common" },
  { name:"Языки", attr:"smarts", base:true, categ:"common" },
  { name:"Анализ", attr:"smarts", base:true, categ:"common" },
  { name:"Знание Нижнего Мира", attr:"smarts", base:true, categ:"common" },
  { name:"Эмпатия", attr:"spirit", base:true, categ:"common" },
  { name:"Самоконтроль", attr:"spirit", base:true, categ:"learned" },
  { name:"Убеждение", attr:"spirit", base:true, categ:"common" },
  { name:"Обман", attr:"spirit", base:true, categ:"learned" },
  { name:"Запугивание", attr:"spirit", base:true, categ:"common" },
  { name:"Исполнение", attr:"spirit", base:true, categ:"common" },
  { name:"Медитация", attr:"spirit", base:false, categ:"learned" },
  { name:"Интуиция", attr:"magic", base:true, categ:"common" },
  { name:"Рукопашный бой", attr:"agility", base:true, categ:"common" },
  { name:"Кулинария", attr:"agility", base:true, categ:"learned" },
  { name:"Скрытность", attr:"agility", base:true, categ:"common" },
  { name:"Координация", attr:"agility", base:true, categ:"common" },
  { name:"Тактика", attr:"smarts", base:false, categ:"learned" },
  { name:"Логические игры", attr:"smarts", base:false, categ:"learned" },
  { name:"Этикет", attr:"smarts", base:false, categ:"learned" },
  { name:"Знание Верхнего Мира", attr:"smarts", base:false, categ:"learned" },
  { name:"Манипуляция", attr:"smarts", base:false, categ:"learned" },
  { name:"Системы безопасности", attr:"smarts", base:false, categ:"learned" },
  { name:"Токсикология", attr:"smarts", base:false, categ:"learned" },
  { name:"Медицина", attr:"smarts", base:false, categ:"learned" },
  { name:"Расследование", attr:"smarts", base:false, categ:"common" },
  { name:"Big Data", attr:"smarts", base:false, categ:"learned" },
  { name:"Программирование", attr:"smarts", base:false, categ:"learned" },
  { name:"Информационная безопасность", attr:"smarts", base:false, categ:"learned" },
  { name:"Хакинг", attr:"smarts", base:false, categ:"learned" },
  { name:"Криптография", attr:"smarts", base:false, categ:"learned" },
  { name:"Профайлинг", attr:"smarts", base:false, categ:"learned" },
  { name:"Актерское мастерство", attr:"spirit", base:false, categ:"learned" },
  { name:"Политология", attr:"smarts", base:false, categ:"learned" },
  { name:"Риторика", attr:"smarts", base:false, categ:"learned" },
  { name:"Инженерия", attr:"smarts", base:false, categ:"learned" },
  { name:"Военные технологии", attr:"smarts", base:false, categ:"learned" },
  { name:"Юриспруденция", attr:"smarts", base:false, categ:"learned" },
  { name:"Владение клинковым оружием", attr:"agility", base:false, categ:"learned" },
  { name:"Владение древковым оружием", attr:"agility", base:false, categ:"learned" },
  { name:"Владение метательным/стрелковым оружием", attr:"agility", base:false, categ:"learned" },
  { name:"Владение огнестрельным оружием", attr:"agility", base:false, categ:"learned" },
  { name:"Артиллерия", attr:"agility", base:false, categ:"learned" },
  { name:"Дроны", attr:"agility", base:false, categ:"learned" },
  { name:"Вождение летательных средств", attr:"agility", base:false, categ:"learned" },
  { name:"Воровство", attr:"agility", base:false, categ:"learned" },
  { name:"Танец", attr:"agility", base:false, categ:"learned" },
  { name:"Восточное искусство", attr:"agility", base:false, categ:"learned" },
  { name:"Боевые искусства", attr:"agility", base:false, categ:"learned" },
  { name:"Секс", attr:"agility", base:false, categ:"common" },
  { name:"Маскировка", attr:"agility", base:false, categ:"learned" },
  { name:"Вождение авто/мото техники", attr:"agility", base:false, categ:"learned" },
  { name:"Вождение специальных средств", attr:"agility", base:false, categ:"learned" },
  { name:"Массаж", attr:"agility", base:false, categ:"learned" },
  { name:"Первая помощь", attr:"agility", base:false, categ:"learned" },
  { name:"Сопротивление боли", attr:"endurance", base:false, categ:"learned" },
  { name:"Сопротивление магии", attr:"endurance", base:false, categ:"learned" },
  { name:"Выживание", attr:"endurance", base:false, categ:"learned" },
  { name:"Сопротивление ментальному давлению", attr:"spirit", base:false, categ:"learned" },
  { name:"Ведение допросов", attr:"spirit", base:false, categ:"learned" },
  { name:"Пытки и казни", attr:"spirit", base:false, categ:"learned" },
  { name:"Лидерство", attr:"spirit", base:false, categ:"learned" },
  { name:"Соблазнение", attr:"spirit", base:false, categ:"learned" },
  { name:"Хладнокровие", attr:"spirit", base:false, categ:"learned" },
  { name:"Внешний вид", attr:"spirit", base:false, categ:"learned" },
  { name:"Концентрация", attr:"spirit", base:false, categ:"learned" },
  { name:"Дрессировка", attr:"spirit", base:false, categ:"learned" },
  { name:"Артефактология", attr:"magic", base:false, categ:"learned" },
  { name:"Определение Магии", attr:"magic", base:false, categ:"learned" },
  { name:"Ритуалистика", attr:"magic", base:false, categ:"learned" },
  { name:"Владение магическими проводниками", attr:"magic", base:false, categ:"learned" },
  { name:"Прорицание", attr:"magic", base:false, categ:"magic" },
  { name:"Целительство", attr:"magic", base:false, categ:"magic" },
  { name:"Алхимия", attr:"magic", base:false, categ:"magic" },
  { name:"Магозоология", attr:"magic", base:false, categ:"magic" },
  { name:"Теория магии", attr:"magic", base:false, categ:"learned" },
  { name:"Матрицалогия - теория", attr:"magic", base:false, categ:"learned" },
  { name:"Техномантия", attr:"magic", base:false, categ:"magic" },
  { name:"Ментальная магия", attr:"magic", base:false, categ:"magic" },
  { name:"Даймонология", attr:"magic", base:false, categ:"magic" },
  { name:"Инфильтрация", attr:"smarts", base:false, categ:"learned" },
  { name:"Агентурная сеть", attr:"smarts", base:false, categ:"learned" },
  { name:"Яды и противоядия", attr:"smarts", base:false, categ:"learned" },
  { name:"Викка", attr:"smarts", base:false, categ:"magic" },
  { name:"Некромантия", attr:"magic", base:false, categ:"magic" },
  { name:"Вампиризм", attr:"agility", base:false, categ:"magic" },
  { name:"Оборотничество", attr:"endurance", base:false, categ:"magic" },
  { name:"Пиромантия", attr:"magic", base:false, categ:"magic" },
  { name:"Эмпирей", attr:"magic", base:false, categ:"magic" },
  { name:"Матрицалогия", attr:"magic", base:false, categ:"magic" },
  { name:"Зеркало вампира", attr:"endurance", base:false, categ:"magic" },
  { name:"Псионика", attr:"spirit", base:false, categ:"magic" },
  { name:"Жречество", attr:"magic", base:false, categ:"magic" },
  { name:"Гламур", attr:"magic", base:false, categ:"magic" },
];

// Навыки чистой карточки: только base, нетренированные d4-2.
export function buildBaseSkills() {
  return SKILLS_DATA
    .filter((s) => s.base)
    .map((s) => ({ name: s.name, attr: s.attr, categ: s.categ, die: 4, modifier: -2 }));
}
