// КК9 — Стартовые данные: Заклинания (полный порт из docs/OldCode/kk9, 1-1 поля)
// spellType: attack / defense / buff / health_buff / binding / spatial / transforming / prophetic / utility
// duration: 0 = мгновенное, -1 = длительное (см. durationHours)
// soakType: "absolute" (поглощает N урона, capacity/current) | "bonus" (+кубик soak) | "status" (щит-статус)
// bypassSoak: бьёт только сквозь абсолютную защиту · unresistable: игнорирует soak и сопротивление
// bonuses: { <attr>: n } (для buff) · toughnessBonus: бонус к стойкости (для defense) · skillBonuses: { "<навык>": n }
// upkeepCost: энергия/раунд для поддержания · uses: заряды в день · noWandNeeded: каст без кольца/жезла

export const SPELLS_DATA = [

  // ══ Концентрация ══
  { name: "Мануэла", img: "icons/svg/aura.svg", spellType: "utility", cost: 1, range: 3, duration: 0, durationHours: 0, uses: 1, skillName: "Концентрация", noWandNeeded: false, effectColor: "#c4b5a0", effectDescription: "Едва заметное мерцание на кончиках пальцев", snakeEyesStatusName: "", description: "Простейшие бытовые магические манипуляции — зажечь, запереть, отпереть, осветить, починить мелкое." },

  // ══ Координация ══
  { name: "Суспендо", img: "icons/svg/fly.svg", spellType: "spatial", cost: 2, range: 10, duration: -1, durationHours: 0, uses: 1, skillName: "Координация", noWandNeeded: false, effectColor: "#8fb8d4", effectDescription: "Тонкие нити серебристого света вокруг предмета", snakeEyesStatusName: "", upkeepCost: 1, description: "Поднять и удерживать предмет в воздухе или притянуть к себе. Предмет не тяжелее кастующего." },
  { name: "Аскендо", img: "icons/svg/fly.svg", spellType: "spatial", cost: 3, range: 0, duration: -1, durationHours: 0, uses: 1, skillName: "Координация", noWandNeeded: false, effectColor: "#8fb8d4", effectDescription: "Свечение под ногами, лёгкий вихрь", snakeEyesStatusName: "", upkeepCost: 2, description: "Подняться в воздух и удерживаться на высоте не более метра над землёй." },

  // ══ Ориентирование ══
  { name: "Яну", img: "icons/svg/door.svg", spellType: "spatial", cost: 10, range: 0, duration: -1, durationHours: 0, uses: 1, skillName: "Ориентирование", noWandNeeded: false, effectColor: "#7c3aed", effectDescription: "Мерцающие ворота с арочными краями, внутри — искажение пространства", snakeEyesStatusName: "", upkeepCost: 3, description: "Открыть проход между двумя точками пространства в виде светящихся ворот." },

  // ══ Эмпатия ══
  { name: "Аудио", img: "icons/svg/sound.svg", spellType: "binding", cost: 3, range: 0, duration: -1, durationHours: 0, uses: 1, skillName: "Эмпатия", noWandNeeded: false, effectColor: "#6d9eeb", effectDescription: "Тёплое золотое свечение вокруг головы", snakeEyesStatusName: "", unresistable: true, description: "Установить магическую связь с известным согласным существом, находящимся в Верхнем мире. +1 энергия за каждые 10км расстояния." },
  { name: "Суссурро", img: "icons/svg/sound.svg", spellType: "binding", cost: 1, range: 50, duration: 0, durationHours: 0, uses: 1, skillName: "Эмпатия", noWandNeeded: false, effectColor: "#7bafd4", effectDescription: "Едва слышимый звон, лёгкое серебро у уха", snakeEyesStatusName: "", unresistable: true, description: "Передать одну фразу телепатически согласному существу в пределах 50м." },

  // ══ Концентрация ══
  { name: "Вокс Омниум", img: "icons/svg/sound.svg", spellType: "binding", cost: 4, range: 15000, duration: -1, durationHours: 0.5, uses: 1, skillName: "Концентрация", noWandNeeded: false, effectColor: "#4a90d9", effectDescription: "Мерцание на глазах кастующего и получателей, лёгкое синее свечение век", snakeEyesStatusName: "", unresistable: true, description: "Передать вид из глаз кастующего группе существ в радиусе 15км." },

  // ══ Интуиция ══
  { name: "Мунимен", img: "icons/svg/shield.svg", spellType: "defense", cost: 2, range: 0, duration: -1, durationHours: 0, uses: 5, skillName: "Интуиция", noWandNeeded: false, effectColor: "#4caf50", effectDescription: "Полупрозрачный щит с мерцающей поверхностью вокруг тела", snakeEyesStatusName: "", soakType: "status", toughnessBonus: 1, description: "Создать магический щит вокруг тела, повышающий стойкость к физическому урону. Бонус применяется к броскам стойкости." },

  // ══ Координация ══
  { name: "Эксармо", img: "icons/svg/sword.svg", spellType: "attack", cost: 2, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Координация", noWandNeeded: false, effectColor: "#ff6b35", effectDescription: "Резкая вспышка у руки цели", snakeEyesStatusName: "", damageType: "physical", hasStatus: false, description: "Магически выбить оружие или предмет из рук цели. Не наносит урона." },
  { name: "Акварум", img: "icons/svg/water.svg", spellType: "attack", cost: 2, range: 15, duration: 0, durationHours: 0, uses: 1, skillName: "Координация", noWandNeeded: false, effectColor: "#ff8c42", effectDescription: "Стремительный поток воды из воздуха", snakeEyesStatusName: "", damageType: "physical", hasStatus: false, description: "Вызвать поток воды из воздуха — сбить с ног или залить цель. Наносит физический урон." },
  { name: "Импульсус", img: "icons/svg/push.svg", spellType: "attack", cost: 2, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Координация", noWandNeeded: false, effectColor: "#dc2626", effectDescription: "Волна невидимой силы с видимым искажением воздуха", snakeEyesStatusName: "", damageType: "physical", hasStatus: false, description: "Магически отбросить цель на несколько метров. Наносит физический урон." },

  // ══ Концентрация ══
  { name: "Винкула", img: "icons/svg/net.svg", spellType: "attack", cost: 3, range: 10, duration: -1, durationHours: 0.25, uses: 1, skillName: "Концентрация", noWandNeeded: false, effectColor: "#e74c3c", effectDescription: "Светящиеся верёвки обвиваются вокруг конечностей цели", snakeEyesStatusName: "", damageType: "physical", hasStatus: true, statusName: "Связанность", description: "Сковать цель магическими верёвками — вызывает стан и -2 к ловкости. Длительность 15 минут." },
  { name: "Аугментум", img: "icons/svg/upgrade.svg", spellType: "buff", cost: 2, range: 0, duration: -1, durationHours: 0, uses: 5, skillName: "Концентрация", noWandNeeded: false, effectColor: "#ff7043", effectDescription: "Свечение на руках и оружии", snakeEyesStatusName: "", bonuses: { agility: 0, smarts: 0, spirit: 0, endurance: 0, magic: 0, toughness: 0 }, skillBonuses: [{ skillName: "Рукопашный бой", bonus: 1 }, { skillName: "Владение клинковым оружием", bonus: 1 }, { skillName: "Владение древковым оружием", bonus: 1 }], description: "Усилить физические атаки — рукопашку, клинки, древко. Бонус к броскам соответствующих навыков." },
  { name: "Клауструм", img: "icons/svg/wall.svg", spellType: "spatial", cost: 3, range: 5, duration: -1, durationHours: 0.25, uses: 1, skillName: "Концентрация", noWandNeeded: false, effectColor: "#7986cb", effectDescription: "Полупрозрачная стена с мерцающими краями", snakeEyesStatusName: "", upkeepCost: 1, description: "Непроходимый магический барьер в точке пространства. Блокирует физический проход." },

  // ══ Целительство ══
  { name: "Санацио", img: "icons/svg/heal.svg", spellType: "utility", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#4caf50", effectDescription: "Зелёное тепло разливается от рук", snakeEyesStatusName: "Лёгкая неудача", description: "Снять 1 пип физического урона с цели." },
  { name: "Реститутио", img: "icons/svg/heal.svg", spellType: "utility", cost: 6, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#2e7d32", effectDescription: "Яркая волна зелёного света", snakeEyesStatusName: "Лёгкая неудача", description: "Снять 2 пипа физического урона с цели." },
  { name: "Стабилис", img: "icons/svg/heal.svg", spellType: "utility", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#81c784", effectDescription: "Мягкое золотисто-зелёное свечение", snakeEyesStatusName: "Лёгкая неудача", description: "Вывести цель из нокаута, стабилизировать состояние." },
  { name: "Детоксио", img: "icons/svg/heal.svg", spellType: "utility", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#388e3c", effectDescription: "Зелёные искры вытягиваются из тела", snakeEyesStatusName: "Лёгкая неудача", description: "Снять статус яда или инфекции с цели." },
  { name: "Фригус Санат", img: "icons/svg/heal.svg", spellType: "utility", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#66bb6a", effectDescription: "Прохладное синевато-зелёное свечение", snakeEyesStatusName: "Лёгкая неудача", description: "Снять статус ожога или кровотечения с цели." },
  { name: "Морби Фуга", img: "icons/svg/heal.svg", spellType: "utility", cost: 5, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#43a047", effectDescription: "Золотисто-зелёная волна через тело", snakeEyesStatusName: "Лёгкая неудача", description: "Снять статус болезни с цели." },
  { name: "Пурификацио", img: "icons/svg/heal.svg", spellType: "utility", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#a5d6a7", effectDescription: "Лёгкое зелёное мерцание", snakeEyesStatusName: "Лёгкая неудача", description: "Снять простой статус с цели. Стоимость 3 энергии за каждый снимаемый статус." },
  { name: "Диагносис", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 1, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#c8e6c9", effectDescription: "Зелёные руны проявляются на коже цели", snakeEyesStatusName: "Лёгкая неудача", description: "Получить полную информацию о физическом состоянии цели — статусы, урон, болезни." },
  { name: "Регенерацио", img: "icons/svg/regen.svg", spellType: "buff", cost: 4, range: 0, duration: -1, durationHours: 1, uses: 3, skillName: "Целительство", noWandNeeded: false, effectColor: "#1b5e20", effectDescription: "Медленное пульсирующее зелёное свечение", snakeEyesStatusName: "Лёгкая неудача", description: "Накладывает статус Исцеление — постепенно восстанавливает 1 пип урона со временем." },
  { name: "Аналгезия", img: "icons/svg/heal.svg", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 5, skillName: "Целительство", noWandNeeded: false, effectColor: "#558b2f", effectDescription: "Тёплое приглушённое зелёное свечение", snakeEyesStatusName: "Лёгкая неудача", description: "Бафф эквивалентный штрафам от урона — цель действует как будто на 1 пип урона меньше." },
  { name: "Акцелеро", img: "icons/svg/upgrade.svg", spellType: "utility", cost: 3, range: 0, duration: -1, durationHours: 24, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#33691e", effectDescription: "Ярко-зелёные прожилки света по поверхности", snakeEyesStatusName: "Лёгкая неудача", description: "Ускорить рост костей или растений — кости срастаются за часы, растения за минуты." },
  { name: "Сомнус", img: "icons/svg/sleep.svg", spellType: "binding", cost: 5, range: 5, duration: -1, durationHours: 8, uses: 1, skillName: "Целительство", noWandNeeded: false, effectColor: "#00695c", effectDescription: "Мягкая зелёно-синяя дымка опускается на цель", snakeEyesStatusName: "Лёгкая неудача", contestedSkillName: "Сопротивление ментальному давлению", description: "Погрузить цель в глубокий сон-стазис, все процессы замедляются. Длительность до 8 часов." },

  // ══ Ментальная магия ══
  { name: "Тимос", img: "icons/svg/terror.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#1e3a5f", effectDescription: "Тёмно-синяя дымка перед глазами цели", snakeEyesStatusName: "Деперсонализация", hasStatus: true, statusName: "Страх", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели иррациональный страх. Накладывает статус Страх." },
  { name: "Эвфория", img: "icons/svg/upgrade.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#7986cb", effectDescription: "Мягкое розово-синее свечение вокруг головы", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели состояние эйфории." },
  { name: "Диссоцио", img: "icons/svg/unconscious.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#3949ab", effectDescription: "Размытое синее мерцание вокруг силуэта", snakeEyesStatusName: "Деперсонализация", hasStatus: true, statusName: "Диссоциация", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели диссоциацию — отрыв от реальности." },
  { name: "Психозис", img: "icons/svg/madness.svg", spellType: "binding", cost: 5, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#1a237e", effectDescription: "Хаотичные тёмно-синие вспышки", snakeEyesStatusName: "Деперсонализация", hasStatus: true, statusName: "Психоз", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели острый психоз." },
  { name: "Мания", img: "icons/svg/upgrade.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#283593", effectDescription: "Интенсивное синее свечение, быстрые искры", snakeEyesStatusName: "Деперсонализация", hasStatus: true, statusName: "Мания", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели маниакальное состояние." },
  { name: "Обсессио", img: "icons/svg/madness.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 12, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#303f9f", effectDescription: "Тонкая синяя нить тянется к объекту одержимости", snakeEyesStatusName: "Деперсонализация", hasStatus: true, statusName: "Навязчивая идея", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели навязчивую идею." },
  { name: "Обливио", img: "icons/svg/unconscious.svg", spellType: "binding", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#5c6bc0", effectDescription: "Белая вспышка перед глазами цели", snakeEyesStatusName: "Деперсонализация", hasStatus: true, statusName: "Амнезия", contestedSkillName: "Сопротивление ментальному давлению", description: "Стереть воспоминания о последних нескольких часах. Накладывает статус Амнезия." },
  { name: "Реплацио", img: "icons/svg/unconscious.svg", spellType: "binding", cost: 8, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#4527a0", effectDescription: "Медленное синее свечение на висках", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Заменить конкретное воспоминание цели на другое." },
  { name: "Импера", img: "icons/svg/aura.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 0.25, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#512da8", effectDescription: "Острая синяя вспышка в глазах цели", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели короткий ментальный приказ. Длительность 15 минут." },
  { name: "Доминацио", img: "icons/svg/aura.svg", spellType: "binding", cost: 10, range: 5, duration: -1, durationHours: 1, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#311b92", effectDescription: "Глубокое фиолетово-синее свечение глаз", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Полный контроль разума цели на время. Очень высокая стоимость." },
  { name: "Инспирацио", img: "icons/svg/upgrade.svg", spellType: "buff", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 5, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#5e35b1", effectDescription: "Золотисто-синее свечение вокруг головы", snakeEyesStatusName: "Деперсонализация", description: "Вдохновить цель. Накладывает статус Вдохновение." },
  { name: "Симпатия", img: "icons/svg/aura.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#7e57c2", effectDescription: "Мягкое тёплое синее свечение", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Расположить цель к кастующему — снижает враждебность." },
  { name: "Фасцинацио", img: "icons/svg/aura.svg", spellType: "binding", cost: 5, range: 10, duration: -1, durationHours: 2, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#673ab7", effectDescription: "Переливающееся синее свечение вокруг кастующего", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Очаровать цель — полная симпатия и доверие." },
  { name: "Катарсис", img: "icons/svg/heal.svg", spellType: "utility", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#9575cd", effectDescription: "Синяя волна через голову цели", snakeEyesStatusName: "Деперсонализация", description: "Снять ментальный статус с цели." },
  { name: "Либерацио", img: "icons/svg/heal.svg", spellType: "utility", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#b39ddb", effectDescription: "Спокойное синее свечение, глубокий выдох", snakeEyesStatusName: "Деперсонализация", description: "Снять статус Ментальное истощение с цели." },
  { name: "Эгида Ментис", img: "icons/svg/shield.svg", spellType: "defense", cost: 2, range: 0, duration: -1, durationHours: 0, uses: 5, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#42a5f5", effectDescription: "Полупрозрачная синяя плёнка вокруг головы", snakeEyesStatusName: "Деперсонализация", soakType: "status", toughnessBonus: 1, description: "Щит от ментального воздействия — бонус к стойкости против ментальных атак." },
  { name: "Детектио", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#64b5f6", effectDescription: "Синие руны кратко проявляются на висках", snakeEyesStatusName: "Деперсонализация", description: "Проверить есть ли на цели ментальные приказы или внушения." },
  { name: "Фантазма", img: "icons/svg/aura.svg", spellType: "utility", cost: 4, range: 15, duration: -1, durationHours: 0.5, uses: 3, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#90caf9", effectDescription: "Мерцающий синеватый силуэт в воздухе", snakeEyesStatusName: "Деперсонализация", description: "Создать иллюзию в пространстве — визуальный образ без физической формы." },
  { name: "Ментис Иктус", img: "icons/svg/lightning.svg", spellType: "attack", cost: 3, range: 15, duration: 0, durationHours: 0, uses: 1, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#1565c0", effectDescription: "Острая синяя вспышка между кастующим и целью", snakeEyesStatusName: "Деперсонализация", damageType: "mental", hasStatus: false, description: "Ментальный удар — наносит ментальный урон цели." },
  { name: "Телепатия", img: "icons/svg/aura.svg", spellType: "binding", cost: 3, range: 5, duration: -1, durationHours: 0.25, uses: 3, skillName: "Ментальная магия", noWandNeeded: false, effectColor: "#4a90d9", effectDescription: "Едва заметное синее свечение вокруг висков", snakeEyesStatusName: "Деперсонализация", contestedSkillName: "Сопротивление ментальному давлению", description: "Читать поверхностные мысли цели. Нарративно — ГМ описывает что слышит кастующий." },

  // ══ Прорицание ══
  { name: "Клэрвойянс", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 4, range: 0, duration: -1, durationHours: 0.25, uses: 3, skillName: "Прорицание", noWandNeeded: false, effectColor: "#7c3aed", effectDescription: "Глаза кастующего светятся фиолетовым", snakeEyesStatusName: "Слепота", description: "Увидеть удалённое место в реальном времени." },
  { name: "Аура Видео", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 1, range: 5, duration: 0, durationHours: 0, uses: 1, skillName: "Прорицание", noWandNeeded: false, effectColor: "#8b5cf6", effectDescription: "Фиолетовое свечение вокруг силуэта цели", snakeEyesStatusName: "Слепота", description: "Почувствовать ауру цели — магический статус, общие намерения, эмоциональный фон." },
  { name: "Окультус", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 5, range: 10, duration: -1, durationHours: 0.25, uses: 3, skillName: "Прорицание", noWandNeeded: false, effectColor: "#6d28d9", effectDescription: "Фиолетовая плёнка на глазах кастующего", snakeEyesStatusName: "Слепота", description: "Видеть скрытые объекты и существа — невидимость не работает против этого заклинания." },
  { name: "Мемориа Плаци", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 5, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Прорицание", noWandNeeded: false, effectColor: "#5b21b6", effectDescription: "Полупрозрачные образы прошлого проявляются в пространстве", snakeEyesStatusName: "Глухота", description: "Заглянуть в прошлое места — увидеть значимые события произошедшие здесь." },
  { name: "Оракулум", img: "icons/svg/aura.svg", spellType: "prophetic", cost: 6, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Прорицание", noWandNeeded: false, effectColor: "#4c1d95", effectDescription: "Вспышка белого с фиолетовым, образы в воздухе", snakeEyesStatusName: "Глухота", description: "Получить смутный образ ближайшего будущего. Интерпретация за ГМом." },
  { name: "Идентифико", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Прорицание", noWandNeeded: false, effectColor: "#7e22ce", effectDescription: "Фиолетовые руны проявляются на поверхности", snakeEyesStatusName: "Глухота", description: "Определить тип и источник заклинания на объекте или акторе." },
  { name: "Вестигиум", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 3, skillName: "Прорицание", noWandNeeded: false, effectColor: "#9333ea", effectDescription: "Светящаяся фиолетовая дорожка видимая только кастующему", snakeEyesStatusName: "Глухота", description: "Найти и следовать магическому следу существа или заклинания." },
  { name: "Локатор", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 4, range: 0, duration: -1, durationHours: 0.25, uses: 1, skillName: "Прорицание", noWandNeeded: false, effectColor: "#a855f7", effectDescription: "Фиолетовая стрелка или свечение в направлении цели", snakeEyesStatusName: "Глухота", description: "Определить направление к известному существу или предмету." },

  // ══ Пиромантия ══
  { name: "Игнис Глобус", img: "icons/svg/fire.svg", spellType: "attack", cost: 5, range: 20, duration: 0, durationHours: 0, uses: 1, skillName: "Пиромантия", noWandNeeded: false, effectColor: "#ef4444", effectDescription: "Взрыв оранжево-красного пламени", snakeEyesStatusName: "Ожог", isAoe: true, damageType: "physical", hasStatus: false, description: "Огненный шар поражающий всех в зоне. Площадное заклинание." },
  { name: "Флamma", img: "icons/svg/fire.svg", spellType: "attack", cost: 3, range: 15, duration: 0, durationHours: 0, uses: 1, skillName: "Пиромантия", noWandNeeded: false, effectColor: "#f97316", effectDescription: "Вытянутый язык пламени от руки кастующего", snakeEyesStatusName: "Ожог", damageType: "physical", hasStatus: false, description: "Струя огня в одну цель." },
  { name: "Комбустио", img: "icons/svg/fire.svg", spellType: "attack", cost: 2, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Пиромантия", noWandNeeded: false, effectColor: "#fb923c", effectDescription: "Вспышка оранжевого на цели", snakeEyesStatusName: "Ожог", damageType: "physical", hasStatus: true, statusName: "Ожог", description: "Поджечь цель — накладывает статус Ожог." },
  { name: "Скутум Игнис", img: "icons/svg/shield.svg", spellType: "defense", cost: 4, range: 0, duration: -1, durationHours: 0, uses: 3, skillName: "Пиромантия", noWandNeeded: false, effectColor: "#dc2626", effectDescription: "Кольцо пламени вращается вокруг кастующего", snakeEyesStatusName: "Ожог", soakType: "status", toughnessBonus: 1, description: "Огненный щит вокруг тела — бонус к стойкости против физических атак. Только на себя." },
  { name: "Карцер Игнис", img: "icons/svg/fire.svg", spellType: "spatial", cost: 6, range: 10, duration: -1, durationHours: 0.25, uses: 1, skillName: "Пиромантия", noWandNeeded: false, effectColor: "#b91c1c", effectDescription: "Стены из пламени образуют клетку вокруг цели", snakeEyesStatusName: "Ожог", upkeepCost: 2, description: "Огненная клетка удерживающая цель внутри — войти и выйти невозможно без урона." },
  { name: "Калор Мурус", img: "icons/svg/aura.svg", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 4, uses: 1, skillName: "Пиромантия", noWandNeeded: false, effectColor: "#fdba74", effectDescription: "Едва заметное тепловое марево вокруг тела", snakeEyesStatusName: "Ожог", description: "Защита от холода и низких температур — цель не страдает от холодового урона и статусов." },

  // ══ Эмпирей ══
  { name: "Бенедиктум", img: "icons/svg/aura.svg", spellType: "buff", cost: 4, range: 0, duration: -1, durationHours: 1, uses: 5, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#f59e0b", effectDescription: "Золотое свечение разливается от рук", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Благословить цель — накладывает статус Благословение. Бонус ко всем броскам и энергии." },
  { name: "Спиритус Форте", img: "icons/svg/aura.svg", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 1, uses: 5, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#fbbf24", effectDescription: "Серебристо-золотое свечение вокруг груди", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Укрепить дух и магический канал цели. Накладывает статус Медитативное состояние." },
  { name: "Виртус", img: "icons/svg/upgrade.svg", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 5, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#d97706", effectDescription: "Тёплое золотое свечение по всему телу", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Даровать физическую силу и выносливость. Накладывает статус Адреналин." },
  { name: "Целеритас", img: "icons/svg/upgrade.svg", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 5, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#f97316", effectDescription: "Золотистые искры вокруг ног и рук", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Ускорить реакцию и инициативу цели. Накладывает статус Повышенная удача." },
  { name: "Магика Ампликацио", img: "icons/svg/aura.svg", spellType: "buff", cost: 4, range: 0, duration: -1, durationHours: 1, uses: 3, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#a855f7", effectDescription: "Золото-фиолетовое свечение вокруг рук", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Усилить магический канал — накладывает статус Медитативное состояние с фокусом на magic." },
  { name: "Малум", img: "icons/svg/curse.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#991b1b", effectDescription: "Тёмно-красное свечение окутывает цель", snakeEyesStatusName: "Одержимость (лёгкая)", hasStatus: true, statusName: "Сглаз", contestedSkillName: "Сопротивление магии", description: "Проклясть цель — накладывает статус Сглаз. Штраф ко всем броскам." },
  { name: "Инфирмитас", img: "icons/svg/downgrade.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 1, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#7f1d1d", effectDescription: "Серое марево оседает на плечи цели", snakeEyesStatusName: "Одержимость (лёгкая)", hasStatus: true, statusName: "Ослабление", contestedSkillName: "Сопротивление магии", description: "Ослабить физические возможности цели — накладывает статус Ослабление." },
  { name: "Фрактус Анимус", img: "icons/svg/downgrade.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#b91c1c", effectDescription: "Тёмно-красная волна через грудь цели", snakeEyesStatusName: "Одержимость (лёгкая)", hasStatus: true, statusName: "Подавленность", contestedSkillName: "Сопротивление магии", description: "Сломить дух цели — накладывает статус Подавленность." },
  { name: "Энергиа Вора", img: "icons/svg/lightning.svg", spellType: "binding", cost: 3, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#dc2626", effectDescription: "Тёмные нити тянутся от цели к кастующему", snakeEyesStatusName: "Одержимость (лёгкая)", contestedSkillName: "Сопротивление магии", description: "Вытянуть энергию из цели — снять N единиц энергии." },
  { name: "Абсолутио", img: "icons/svg/aura.svg", spellType: "utility", cost: 5, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#fde68a", effectDescription: "Яркая золотая вспышка, тёмное облако рассеивается", snakeEyesStatusName: "Одержимость (лёгкая)", description: "Снять проклятие с цели." },
  { name: "Сигиллум", img: "icons/svg/magic.svg", spellType: "binding", cost: 10, range: 0, duration: -1, durationHours: 12, uses: 1, skillName: "Эмпирей", noWandNeeded: false, effectColor: "#78350f", effectDescription: "Светящаяся печать проявляется на коже цели", snakeEyesStatusName: "Одержимость (лёгкая)", hasStatus: true, statusName: "Печать", contestedSkillName: "Сопротивление магии", description: "Заблокировать магические способности цели на 12 часов. Накладывает статус Печать." },

  // ══ Жречество ══
  { name: "Грация", img: "icons/svg/aura.svg", spellType: "buff", cost: 4, range: 0, duration: -1, durationHours: 1, uses: 5, skillName: "Жречество", noWandNeeded: false, effectColor: "#b45309", effectDescription: "Тёплое бронзовое свечение разливается от рук", snakeEyesStatusName: "Паранойя", description: "Даровать благодать бога — накладывает статус Благословение. Бонус ко всем броскам и энергии." },
  { name: "Кларор Белли", img: "icons/svg/upgrade.svg", spellType: "buff", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 5, skillName: "Жречество", noWandNeeded: false, effectColor: "#92400e", effectDescription: "Охристое свечение вспыхивает вокруг группы", snakeEyesStatusName: "Паранойя", description: "Воинский клич — накладывает статус Адреналин всем в радиусе 10м." },
  { name: "Эгида Деорум", img: "icons/svg/shield.svg", spellType: "defense", cost: 3, range: 0, duration: -1, durationHours: 0, uses: 5, skillName: "Жречество", noWandNeeded: false, effectColor: "#78350f", effectDescription: "Бронзовый щит проявляется вокруг тела", snakeEyesStatusName: "Паранойя", soakType: "status", toughnessBonus: 1, description: "Защита богов — бонус к стойкости против любого урона. Только на себя." },
  { name: "Донум Санацио", img: "icons/svg/heal.svg", spellType: "utility", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Жречество", noWandNeeded: false, effectColor: "#065f46", effectDescription: "Золотисто-зелёное свечение от рук", snakeEyesStatusName: "Паранойя", description: "Снять 1 пип физического или ментального урона по воле бога." },
  { name: "Орацио", img: "icons/svg/aura.svg", spellType: "utility", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Жречество", noWandNeeded: false, effectColor: "#d97706", effectDescription: "Тихое бронзовое мерцание вокруг кастующего", snakeEyesStatusName: "Паранойя", description: "Молитва богу — накладывает статус Восстановление энергии." },
  { name: "Дира", img: "icons/svg/curse.svg", spellType: "binding", cost: 5, range: 10, duration: -1, durationHours: 12, uses: 1, skillName: "Жречество", noWandNeeded: false, effectColor: "#7c2d12", effectDescription: "Тёмное охристое облако окутывает цель", snakeEyesStatusName: "Паранойя", hasStatus: true, statusName: "Сглаз", contestedSkillName: "Сопротивление магии", description: "Обрушить проклятие бога на цель — накладывает статус Сглаз." },
  { name: "Кастигацио", img: "icons/svg/downgrade.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Жречество", noWandNeeded: false, effectColor: "#991b1b", effectDescription: "Тёмная печать проявляется на руках цели", snakeEyesStatusName: "Паранойя", hasStatus: true, statusName: "Ослабление", contestedSkillName: "Сопротивление магии", description: "Кара богов — накладывает статус Ослабление на цель." },
  { name: "Ира Деорум", img: "icons/svg/lightning.svg", spellType: "attack", cost: 4, range: 15, duration: 0, durationHours: 0, uses: 1, skillName: "Жречество", noWandNeeded: false, effectColor: "#b45309", effectDescription: "Ослепительная вспышка охры и бронзы", snakeEyesStatusName: "Паранойя", damageType: "mental", hasStatus: false, description: "Обрушить гнев бога — ментальный урон от страха перед divine силой." },
  { name: "Консекрацио", img: "icons/svg/aura.svg", spellType: "spatial", cost: 6, range: 5, duration: -1, durationHours: 24, uses: 1, skillName: "Жречество", noWandNeeded: false, effectColor: "#a16207", effectDescription: "Бронзовые руны проявляются на полу и стенах", snakeEyesStatusName: "Паранойя", description: "Освятить место — защитный ритуал на территорию, враждебная магия ослаблена." },
  { name: "Инвокацио", img: "icons/svg/aura.svg", spellType: "utility", cost: 5, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Жречество", noWandNeeded: false, effectColor: "#d97706", effectDescription: "Голос в голове, запах ладана, бронзовое свечение", snakeEyesStatusName: "Паранойя", description: "Прямой запрос к богу — ответ нарративно за ГМом." },

  // ══ Гламур ══
  { name: "Морфэ", img: "icons/svg/aura.svg", spellType: "transforming", cost: 4, range: 0, duration: -1, durationHours: 2, uses: 1, skillName: "Гламур", noWandNeeded: false, effectColor: "#e2e8f0", effectDescription: "Серебристая рябь по коже как по воде", snakeEyesStatusName: "Зависимость", description: "Изменить внешность себя или другого — лицо, рост, цвет волос." },
  { name: "Акусма", img: "icons/svg/sound.svg", spellType: "utility", cost: 2, range: 20, duration: -1, durationHours: 0.25, uses: 3, skillName: "Гламур", noWandNeeded: false, effectColor: "#f1f5f9", effectDescription: "Едва заметное перламутровое мерцание в воздухе", snakeEyesStatusName: "Зависимость", description: "Создать иллюзию звука в любой точке пространства." },
  { name: "Инвизибилис", img: "icons/svg/aura.svg", spellType: "spatial", cost: 5, range: 0, duration: -1, durationHours: 0.5, uses: 1, skillName: "Гламур", noWandNeeded: false, effectColor: "#cbd5e1", effectDescription: "Силуэт растворяется в воздухе с перламутровым отблеском", snakeEyesStatusName: "Зависимость", description: "Сделать цель полностью невидимой." },
  { name: "Фантазма Рей", img: "icons/svg/aura.svg", spellType: "utility", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Гламур", noWandNeeded: false, effectColor: "#e0f2fe", effectDescription: "Перламутровый контур заполняется образом", snakeEyesStatusName: "Зависимость", description: "Создать иллюзию предмета — выглядит и звучит реально, потрогать нельзя." },
  { name: "Венустас", img: "icons/svg/upgrade.svg", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 1, uses: 5, skillName: "Гламур", noWandNeeded: false, effectColor: "#fce7f3", effectDescription: "Розово-серебристое свечение вокруг фигуры", snakeEyesStatusName: "Зависимость", description: "Бонус к социальным навыкам — цель кажется неотразимой." },
  { name: "Фидуция", img: "icons/svg/aura.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Гламур", noWandNeeded: false, effectColor: "#fbcfe8", effectDescription: "Тёплое розовое свечение между кастующим и целью", snakeEyesStatusName: "Зависимость", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели безусловное доверие к кастующему." },
  { name: "Игнотус", img: "icons/svg/aura.svg", spellType: "utility", cost: 2, range: 0, duration: -1, durationHours: 0.5, uses: 3, skillName: "Гламур", noWandNeeded: false, effectColor: "#f8fafc", effectDescription: "Серебристая дымка оседает на плечи кастующего", snakeEyesStatusName: "Зависимость", description: "Стать незаметным — никто не обращает внимания. Не невидимость." },
  { name: "Галлюцинацио", img: "icons/svg/madness.svg", spellType: "binding", cost: 5, range: 10, duration: -1, durationHours: 0.25, uses: 1, skillName: "Гламур", noWandNeeded: false, effectColor: "#e879f9", effectDescription: "Хаотичные перламутровые вспышки вокруг головы цели", snakeEyesStatusName: "Зависимость", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели яркую галлюцинацию — видит и слышит то чего нет." },
  { name: "Окультацио Магикэ", img: "icons/svg/aura.svg", spellType: "utility", cost: 3, range: 0, duration: -1, durationHours: 2, uses: 1, skillName: "Гламур", noWandNeeded: false, effectColor: "#f0f9ff", effectDescription: "Тонкая серебристая плёнка, почти незаметная", snakeEyesStatusName: "Зависимость", description: "Скрыть магический след на существе или предмете — Прорицание не найдёт." },

  // ══ Викка ══
  { name: "Флора Доминум", img: "icons/svg/plant.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 3, skillName: "Викка", noWandNeeded: false, effectColor: "#15803d", effectDescription: "Зелёные прожилки света бегут по стеблям", snakeEyesStatusName: "Звериная ярость", contestedSkillName: "Сопротивление магии", description: "Подчинить растение — двигать ветвями, атаковать лозами, удерживать цель." },
  { name: "Токсика Херба", img: "icons/svg/poison.svg", spellType: "attack", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#166534", effectDescription: "Тёмно-зелёная вспышка на точке касания", snakeEyesStatusName: "Звериная ярость", damageType: "physical", hasStatus: true, statusName: "Отравление", description: "Извлечь яд из растения и применить к цели — накладывает статус Отравление." },
  { name: "Лингва Бестиэ", img: "icons/svg/aura.svg", spellType: "utility", cost: 2, range: 5, duration: -1, durationHours: 0.5, uses: 3, skillName: "Викка", noWandNeeded: false, effectColor: "#4ade80", effectDescription: "Мягкое зелёное свечение вокруг рта кастующего", snakeEyesStatusName: "Звериная ярость", description: "Говорить с животным — понимать и быть понятым." },
  { name: "Доминус Бестиэ", img: "icons/svg/aura.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#16a34a", effectDescription: "Зелёные нити тянутся от руки к животному", snakeEyesStatusName: "Звериная ярость", contestedSkillName: "Сопротивление магии", description: "Подчинить животное — полное управление действиями." },
  { name: "Вокацио Бестиэ", img: "icons/svg/aura.svg", spellType: "utility", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#22c55e", effectDescription: "Низкий природный звук, зелёное мерцание", snakeEyesStatusName: "Звериная ярость", description: "Призвать ближайшее животное определённого вида." },
  { name: "Небула", img: "icons/svg/aura.svg", spellType: "spatial", cost: 3, range: 20, duration: -1, durationHours: 0.5, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#6b7280", effectDescription: "Серо-зелёный туман поднимается от земли", snakeEyesStatusName: "Звериная ярость", upkeepCost: 1, description: "Вызвать густой туман в зоне — видимость резко падает." },
  { name: "Аура Вентус", img: "icons/svg/wind.svg", spellType: "attack", cost: 3, range: 15, duration: 0, durationHours: 0, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#84cc16", effectDescription: "Вихрь серо-зелёного воздуха", snakeEyesStatusName: "Звериная ярость", damageType: "physical", hasStatus: false, description: "Управлять ветром — сбить с ног или отбросить цель." },
  { name: "Фульмен", img: "icons/svg/lightning.svg", spellType: "attack", cost: 5, range: 20, duration: 0, durationHours: 0, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#a3e635", effectDescription: "Ослепительная белая молния с зелёным отблеском", snakeEyesStatusName: "Звериная ярость", damageType: "physical", hasStatus: true, statusName: "Электрошок", description: "Вызвать молнию — мощная атака, накладывает статус Электрошок." },
  { name: "Терра Потестас", img: "icons/svg/aura.svg", spellType: "attack", cost: 4, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#713f12", effectDescription: "Земля трескается, коричнево-зелёные волны", snakeEyesStatusName: "Звериная ярость", damageType: "physical", hasStatus: false, description: "Управлять землёй — поднять барьер или обрушить почву на цель." },
  { name: "Мутацио Темпестас", img: "icons/svg/wind.svg", spellType: "utility", cost: 8, range: 0, duration: -1, durationHours: 4, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#374151", effectDescription: "Тёмные тучи собираются, природа реагирует", snakeEyesStatusName: "Звериная ярость", description: "Изменить погоду в радиусе нескольких километров — дождь, ветер, туман." },
  { name: "Спина Винкула", img: "icons/svg/net.svg", spellType: "attack", cost: 4, range: 10, duration: -1, durationHours: 0.25, uses: 1, skillName: "Викка", noWandNeeded: false, effectColor: "#14532d", effectDescription: "Тёмно-зелёные лозы с шипами обвивают цель", snakeEyesStatusName: "Звериная ярость", damageType: "physical", hasStatus: true, statusName: "Связанность", description: "Опутать цель терновыми лозами — стан + урон от шипов при каждом движении." },

  // ══ Некромантия ══
  { name: "Сурге", img: "icons/svg/skull.svg", spellType: "utility", cost: 5, range: 0, duration: -1, durationHours: 0, uses: 1, skillName: "Некромантия", noWandNeeded: false, effectColor: "#365314", effectDescription: "Зеленоватое свечение проникает в тело, глаза светятся", snakeEyesStatusName: "Некроз (начальный)", upkeepCost: 2, description: "Поднять мертвеца — заставить тело двигаться и выполнять команды." },
  { name: "Реквием", img: "icons/svg/skull.svg", spellType: "utility", cost: 3, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Некромантия", noWandNeeded: false, effectColor: "#4b5563", effectDescription: "Серое свечение гаснет, тело оседает", snakeEyesStatusName: "Некроз (начальный)", description: "Упокоить поднятого мертвеца или беспокойного духа." },
  { name: "Мортис Легере", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Некромантия", noWandNeeded: false, effectColor: "#6b7280", effectDescription: "Серо-зелёные руны проявляются на теле", snakeEyesStatusName: "Некроз (начальный)", description: "Определить как и когда умерло существо." },
  { name: "Мурус Мортис", img: "icons/svg/wall.svg", spellType: "spatial", cost: 5, range: 5, duration: -1, durationHours: 0.5, uses: 1, skillName: "Некромантия", noWandNeeded: false, effectColor: "#374151", effectDescription: "Серые силуэты образуют стену", snakeEyesStatusName: "Некроз (начальный)", upkeepCost: 2, description: "Барьер из мертвецов — нежить не может пройти." },
  { name: "Эгида Мортуорум", img: "icons/svg/shield.svg", spellType: "defense", cost: 4, range: 0, duration: -1, durationHours: 0, uses: 3, skillName: "Некромантия", noWandNeeded: false, effectColor: "#1f2937", effectDescription: "Серо-зелёная плёнка из призрачных рук вокруг тела", snakeEyesStatusName: "Некроз (начальный)", soakType: "absolute", soakAbsoluteCapacity: 2, description: "Щит из мёртвой плоти — абсолютная защита от физического урона. Только на себя." },
  { name: "Некротикус Армис", img: "icons/svg/sword.svg", spellType: "buff", cost: 3, range: 0, duration: -1, durationHours: 0.5, uses: 5, skillName: "Некромантия", noWandNeeded: false, effectColor: "#14532d", effectDescription: "Тёмно-зелёное свечение по лезвию", snakeEyesStatusName: "Некроз (начальный)", description: "Покрыть оружие некротической энергией — при ударе накладывает Некроз (начальный)." },
  { name: "Лингва Умбрэ", img: "icons/svg/aura.svg", spellType: "utility", cost: 3, range: 5, duration: -1, durationHours: 0.25, uses: 3, skillName: "Некромантия", noWandNeeded: false, effectColor: "#6b7280", effectDescription: "Холодный серый туман, голос из ниоткуда", snakeEyesStatusName: "Некроз (начальный)", description: "Говорить с призраком — воспринимать и передавать слова духа." },
  { name: "Вокацио Умбрэ", img: "icons/svg/aura.svg", spellType: "binding", cost: 5, range: 0, duration: -1, durationHours: 0.5, uses: 1, skillName: "Некромантия", noWandNeeded: false, effectColor: "#4b5563", effectDescription: "Серый силуэт проявляется из воздуха", snakeEyesStatusName: "Некроз (начальный)", description: "Вызвать призрака конкретного умершего." },
  { name: "Мемориа Мортис", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Некромантия", noWandNeeded: false, effectColor: "#374151", effectDescription: "Образы из прошлого мертвеца проявляются в воздухе", snakeEyesStatusName: "Некроз (начальный)", description: "Прочитать последние воспоминания мертвеца." },
  { name: "Адвентус Мортис", img: "icons/svg/skull.svg", spellType: "utility", cost: 12, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Некромантия", noWandNeeded: false, effectColor: "#111827", effectDescription: "Абсолютная тьма, тишина, запах тлена", snakeEyesStatusName: "Некроз (начальный)", description: "Призвать смерть — нарративный эффект определяет ГМ. Очень высокая стоимость." },

  // ══ Псионика ══
  { name: "Тимос Псике", img: "icons/svg/terror.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e3a5f", effectDescription: "Тёмно-синяя дымка перед глазами цели", snakeEyesStatusName: "Паника", hasStatus: true, statusName: "Страх", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели иррациональный страх." },
  { name: "Эвфория Псике", img: "icons/svg/upgrade.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#3730a3", effectDescription: "Мягкое розово-синее свечение вокруг головы", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели состояние эйфории." },
  { name: "Диссоцио Псике", img: "icons/svg/unconscious.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e1b4b", effectDescription: "Размытое синее мерцание вокруг силуэта", snakeEyesStatusName: "Паника", hasStatus: true, statusName: "Диссоциация", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели диссоциацию — отрыв от реальности." },
  { name: "Психозис Псике", img: "icons/svg/madness.svg", spellType: "binding", cost: 5, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#172554", effectDescription: "Хаотичные тёмно-синие вспышки", snakeEyesStatusName: "Паника", hasStatus: true, statusName: "Психоз", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели острый психоз." },
  { name: "Мания Псике", img: "icons/svg/upgrade.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e3a8a", effectDescription: "Интенсивное синее свечение, быстрые искры", snakeEyesStatusName: "Паника", hasStatus: true, statusName: "Мания", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели маниакальное состояние." },
  { name: "Обсессио Псике", img: "icons/svg/madness.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 12, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1d4ed8", effectDescription: "Тонкая синяя нить тянется к объекту одержимости", snakeEyesStatusName: "Паника", hasStatus: true, statusName: "Навязчивая идея", contestedSkillName: "Сопротивление ментальному давлению", description: "Вызвать у цели навязчивую идею." },
  { name: "Обливио Псике", img: "icons/svg/unconscious.svg", spellType: "binding", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e40af", effectDescription: "Белая вспышка перед глазами цели", snakeEyesStatusName: "Паника", hasStatus: true, statusName: "Амнезия", contestedSkillName: "Сопротивление ментальному давлению", description: "Стереть воспоминания о последних нескольких часах." },
  { name: "Реплацио Псике", img: "icons/svg/unconscious.svg", spellType: "binding", cost: 8, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e3a5f", effectDescription: "Медленное синее свечение на висках", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Заменить конкретное воспоминание цели на другое." },
  { name: "Импера Псике", img: "icons/svg/aura.svg", spellType: "binding", cost: 4, range: 10, duration: -1, durationHours: 0.25, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#2563eb", effectDescription: "Острая синяя вспышка в глазах цели", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Внушить цели короткий ментальный приказ." },
  { name: "Доминацио Псике", img: "icons/svg/aura.svg", spellType: "binding", cost: 10, range: 5, duration: -1, durationHours: 1, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e1b4b", effectDescription: "Глубокое фиолетово-синее свечение глаз", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Полный контроль разума цели на время." },
  { name: "Инспирацио Псике", img: "icons/svg/upgrade.svg", spellType: "buff", cost: 3, range: 10, duration: -1, durationHours: 0.5, uses: 5, skillName: "Псионика", noWandNeeded: false, effectColor: "#1d4ed8", effectDescription: "Золотисто-синее свечение вокруг головы", snakeEyesStatusName: "Паника", description: "Вдохновить цель. Накладывает статус Вдохновение." },
  { name: "Симпатия Псике", img: "icons/svg/aura.svg", spellType: "binding", cost: 3, range: 10, duration: -1, durationHours: 1, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#2563eb", effectDescription: "Мягкое тёплое синее свечение", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Расположить цель к кастующему — снижает враждебность." },
  { name: "Фасцинацио Псике", img: "icons/svg/aura.svg", spellType: "binding", cost: 5, range: 10, duration: -1, durationHours: 2, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e3a8a", effectDescription: "Переливающееся синее свечение вокруг кастующего", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Очаровать цель — полная симпатия и доверие." },
  { name: "Катарсис Псике", img: "icons/svg/heal.svg", spellType: "utility", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1d4ed8", effectDescription: "Синяя волна через голову цели", snakeEyesStatusName: "Паника", description: "Снять ментальный статус с цели." },
  { name: "Либерацио Псике", img: "icons/svg/heal.svg", spellType: "utility", cost: 4, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e40af", effectDescription: "Спокойное синее свечение, глубокий выдох", snakeEyesStatusName: "Паника", description: "Снять статус Ментальное истощение с цели." },
  { name: "Эгида Псике", img: "icons/svg/shield.svg", spellType: "defense", cost: 2, range: 0, duration: -1, durationHours: 0, uses: 5, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e3a5f", effectDescription: "Полупрозрачная синяя плёнка вокруг головы", snakeEyesStatusName: "Паника", soakType: "status", toughnessBonus: 1, description: "Щит от ментального воздействия — бонус к стойкости против ментальных атак." },
  { name: "Детектио Псике", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 2, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#2563eb", effectDescription: "Синие руны кратко проявляются на висках", snakeEyesStatusName: "Паника", description: "Проверить есть ли на цели ментальные приказы или внушения." },
  { name: "Ментис Иктус Псике", img: "icons/svg/lightning.svg", spellType: "attack", cost: 3, range: 15, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e3a5f", effectDescription: "Острая синяя вспышка между кастующим и целью", snakeEyesStatusName: "Паника", damageType: "mental", hasStatus: false, description: "Ментальный удар — наносит ментальный урон цели." },
  { name: "Легатус Псике", img: "icons/svg/sound.svg", spellType: "binding", cost: 3, range: 0, duration: -1, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#172554", effectDescription: "Холодное синее свечение вокруг висков", snakeEyesStatusName: "Паника", unresistable: true, description: "Установить псионическую связь с существом в Нижнем мире. +1 энергия за каждые 10км расстояния." },
  { name: "Онейрос", img: "icons/svg/eye.svg", spellType: "prophetic", cost: 3, range: 0, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e3a8a", effectDescription: "Полупрозрачные образы снов проявляются в воздухе", snakeEyesStatusName: "Паника", description: "Подсмотреть текущий или последний сон цели." },
  { name: "Онейропомпос", img: "icons/svg/sleep.svg", spellType: "binding", cost: 4, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#1e40af", effectDescription: "Мягкая синяя дымка оседает на веки цели", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Задать следующий сон цели — не усыпляет, работает когда цель засыпает сама." },
  { name: "Эфиальтес", img: "icons/svg/terror.svg", spellType: "binding", cost: 5, range: 10, duration: 0, durationHours: 0, uses: 1, skillName: "Псионика", noWandNeeded: false, effectColor: "#172554", effectDescription: "Тёмно-синие тени обвивают голову цели", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Наслать кошмар — следующий сон цели будет мучительным." },
  { name: "Телепатия Псике", img: "icons/svg/aura.svg", spellType: "binding", cost: 3, range: 5, duration: -1, durationHours: 0.25, uses: 3, skillName: "Псионика", noWandNeeded: false, effectColor: "#1d4ed8", effectDescription: "Едва заметное синее свечение вокруг висков", snakeEyesStatusName: "Паника", contestedSkillName: "Сопротивление ментальному давлению", description: "Читать поверхностные мысли цели в Нижнем мире. Нарративно — ГМ описывает что слышит кастующий." },
];
